# -*- coding: utf-8 -*-
"""Copy of tugas tik pak heri_luas bangun datar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/143XbrDGEzbikLDIKteroAXODLpAm8NQI
"""

def luas_segitiga(alas, tinggi):
    return 0.5 * alas * tinggi

def luas_persegi(sisi):
    return sisi * sisi

def luas_persegi_panjang(panjang, lebar):
    return panjang * lebar

def luas_lingkaran(jari_jari):
    return 3.141592653589793 * jari_jari * jari_jari

def luas_trapesium(sisi_a, sisi_b, tinggi):
    return 0.5 * (sisi_a + sisi_b) * tinggi

def main():
    nama = input("Masukkan nama Anda: ")
    print(f"Selamat datang, {nama}!")

    while True:
        print("\n=== Program Menghitung Luas Bangun Datar ===")
        print("1. Segitiga")
        print("2. Persegi")
        print("3. Persegi Panjang")
        print("4. Lingkaran")
        print("5. Trapesium")
        print("6. Keluar/Selesai")

        pilihan = input("Pilih bangun datar (1-6): ")

        if pilihan == '1':
            try:
                alas = float(input("Masukkan alas segitiga: "))
                tinggi = float(input("Masukkan tinggi segitiga: "))
                luas = luas_segitiga(alas, tinggi)
                print(f"Luas segitiga: {luas}")
            except ValueError:
                print("Input tidak valid, masukkan angka yang benar.")
        elif pilihan == '2':
            try:
                sisi = float(input("Masukkan sisi persegi: "))
                luas = luas_persegi(sisi)
                print(f"Luas persegi: {luas}")
            except ValueError:
                print("Input tidak valid, masukkan angka yang benar.")
        elif pilihan == '3':
            try:
                panjang = float(input("Masukkan panjang persegi panjang: "))
                lebar = float(input("Masukkan lebar persegi panjang: "))
                luas = luas_persegi_panjang(panjang, lebar)
                print(f"Luas persegi panjang: {luas}")
            except ValueError:
                print("Input tidak valid, masukkan angka yang benar.")
        elif pilihan == '4':
            try:
                jari_jari = float(input("Masukkan jari-jari lingkaran: "))
                luas = luas_lingkaran(jari_jari)
                print(f"Luas lingkaran: {luas}")
            except ValueError:
                print("Input tidak valid, masukkan angka yang benar.")
        elif pilihan == '5':
            try:
                sisi_a = float(input("Masukkan sisi atas trapesium: "))
                sisi_b = float(input("Masukkan sisi bawah trapesium: "))
                tinggi = float(input("Masukkan tinggi trapesium: "))
                luas = luas_trapesium(sisi_a, sisi_b, tinggi)
                print(f"Luas trapesium: {luas}")
            except ValueError:
                print("Input tidak valid, masukkan angka yang benar.")
        elif pilihan == '6':
            print(f"Terima kasih, {nama}. Program selesai.")
            break
        else:
            print("Pilihan tidak dikenali, silakan pilih angka antara 1 sampai 6.")

if __name__ == "__main__":
    main()