# -*- coding: utf-8 -*-
"""PROJECT CHATBOT PMB TIK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16k4MvmHcUWkA0-kzBp3S78ZeMeeEZV-V
"""

import ipywidgets as widgets
from IPython.display import display, clear_output

# Define helper functions for calculating area
def hitung_luas_persegi(sisi):
    return sisi * sisi

def hitung_luas_persegi_panjang(panjang, lebar):
    return panjang * lebar

def hitung_luas_lingkaran(jari_jari):
    return 3.141592653589793 * jari_jari * jari_jari

def hitung_luas_segitiga(alas, tinggi):
    return 0.5 * alas * tinggi

def hitung_luas_jajar_genjang(alas, tinggi):
    return alas * tinggi

def hitung_luas_trapesium(sisi_a, sisi_b, tinggi):
    return 0.5 * (sisi_a + sisi_b) * tinggi

# Widget input untuk nama
input_nama = widgets.Text(
    value='',
    placeholder='Masukkan nama Anda',
    description='Nama:',
    disabled=False
)

btn_mulai = widgets.Button(description="Mulai")
output = widgets.Output()

def mulai_clicked(b):
    with output:
        clear_output()
        nama = input_nama.value.strip()
        if not nama:
            print("Mohon masukkan nama Anda terlebih dahulu.")
            return
        print(f"Halo, {nama}! Silakan pilih bangun datar untuk menghitung luasnya.")
        tampilkan_menu(nama)

def tampilkan_menu(nama):
    pilihan_bangun = widgets.Dropdown(
        options=[
            ('Persegi', 1),
            ('Persegi Panjang', 2),
            ('Lingkaran', 3),
            ('Segitiga', 4),
            ('Jajar Genjang', 5),
            ('Trapesium', 6),
            ('Selesai', 7)
        ],
        description='Bangun:',
        disabled=False,
    )
    btn_hitung = widgets.Button(description='Hitung Luas')
    result_out = widgets.Output()
    ukuran_widgets = []

    def update_ukuran_widgets(change):
        pilihan = change['new']
        # Hapus widget lama
        for w in ukuran_widgets:
            w.close()
        ukuran_widgets.clear()
        result_out.clear_output()

        if pilihan == 1:  # Persegi
            sisi = widgets.FloatText(description='Sisi:', value=0)
            ukuran_widgets.append(sisi)
            display(*ukuran_widgets)

        elif pilihan == 2:  # Persegi Panjang
            panjang = widgets.FloatText(description='Panjang:', value=0)
            lebar = widgets.FloatText(description='Lebar:', value=0)
            ukuran_widgets.extend([panjang, lebar])
            display(*ukuran_widgets)

        elif pilihan == 3:  # Lingkaran
            jari_jari = widgets.FloatText(description='Jari-jari:', value=0)
            ukuran_widgets.append(jari_jari)
            display(*ukuran_widgets)

        elif pilihan == 4:  # Segitiga
            alas = widgets.FloatText(description='Alas:', value=0)
            tinggi = widgets.FloatText(description='Tinggi:', value=0)
            ukuran_widgets.extend([alas, tinggi])
            display(*ukuran_widgets)

        elif pilihan == 5:  # Jajar Genjang
            alas = widgets.FloatText(description='Alas:', value=0)
            tinggi = widgets.FloatText(description='Tinggi:', value=0)
            ukuran_widgets.extend([alas, tinggi])
            display(*ukuran_widgets)

        elif pilihan == 6:  # Trapesium
            sisi_a = widgets.FloatText(description='Sisi a:', value=0)
            sisi_b = widgets.FloatText(description='Sisi b:', value=0)
            tinggi = widgets.FloatText(description='Tinggi:', value=0)
            ukuran_widgets.extend([sisi_a, sisi_b, tinggi])
            display(*ukuran_widgets)

        elif pilihan == 7:  # Selesai
            print(f"Terima kasih {nama}, telah menggunakan program ini.")
            btn_hitung.disabled = True
            pilihan_bangun.disabled = True
            for w in ukuran_widgets:
                w.close()
            ukuran_widgets.clear()

    pilihan_bangun.observe(update_ukuran_widgets, names='value')

    def hitung_area(b):
        result_out.clear_output()
        pilihan = pilihan_bangun.value
        try:
            if pilihan == 1:  # Persegi
                sisi = ukuran_widgets[0].value
                if sisi <= 0:
                    raise ValueError("Sisi harus > 0")
                luas = hitung_luas_persegi(sisi)
                text = f'Luas persegi dengan sisi {sisi} adalah {luas:.2f}'
            elif pilihan == 2:  # Persegi Panjang
                panjang = ukuran_widgets[0].value
                lebar = ukuran_widgets[1].value
                if panjang <= 0 or lebar <= 0:
                    raise ValueError("Panjang dan lebar harus > 0")
                luas = hitung_luas_persegi_panjang(panjang, lebar)
                text = f'Luas persegi panjang {panjang} x {lebar} adalah {luas:.2f}'
            elif pilihan == 3:  # Lingkaran
                jari_jari = ukuran_widgets[0].value
                if jari_jari <= 0:
                    raise ValueError("Jari-jari harus > 0")
                luas = hitung_luas_lingkaran(jari_jari)
                text = f'Luas lingkaran dengan jari-jari {jari_jari} adalah {luas:.2f}'
            elif pilihan == 4:  # Segitiga
                alas = ukuran_widgets[0].value
                tinggi = ukuran_widgets[1].value
                if alas <= 0 or tinggi <= 0:
                    raise ValueError("Alas dan tinggi harus > 0")
                luas = hitung_luas_segitiga(alas, tinggi)
                text = f'Luas segitiga dengan alas {alas} dan tinggi {tinggi} adalah {luas:.2f}'
            elif pilihan == 5:  # Jajar Genjang
                alas = ukuran_widgets[0].value
                tinggi = ukuran_widgets[1].value
                if alas <= 0 or tinggi <= 0:
                    raise ValueError("Alas dan tinggi harus > 0")
                luas = hitung_luas_jajar_genjang(alas, tinggi)
                text = f'Luas jajar genjang dengan alas {alas} dan tinggi {tinggi} adalah {luas:.2f}'
            elif pilihan == 6:  # Trapesium
                sisi_a = ukuran_widgets[0].value
                sisi_b = ukuran_widgets[1].value
                tinggi = ukuran_widgets[2].value
                if sisi_a <= 0 or sisi_b <= 0 or tinggi <= 0:
                    raise ValueError("Sisi a, sisi b, dan tinggi harus > 0")
                luas = hitung_luas_trapesium(sisi_a, sisi_b, tinggi)
                text = f'Luas trapesium dengan sisi a {sisi_a}, sisi b {sisi_b} dan tinggi {tinggi} adalah {luas:.2f}'
            elif pilihan == 7:
                text = f"Terima kasih {nama}, sampai jumpa! perhatian: btn_hitung dan pilihan_bangun dinonaktifkan."
                btn_hitung.disabled = True
                pilihan_bangun.disabled = True
                # Close remaining widgets if any (for safety)
                for w in ukuran_widgets:
                    w.close()
                ukuran_widgets.clear()
            else:
                text = "Pilihan tidak valid."
        except ValueError as e:
            text = f"Error: {str(e)}"
        with result_out:
            print(text)


    display(pilihan_bangun)
    # Call update_ukuran_widgets initially to display widgets for the default choice
    update_ukuran_widgets({'new': pilihan_bangun.value})
    display(btn_hitung)
    display(result_out)
    btn_hitung.on_click(hitung_area)

btn_mulai.on_click(mulai_clicked)
display(input_nama, btn_mulai, output)

import ipywidgets as widgets
from IPython.display import display, clear_output

# Define helper functions for calculating area
def hitung_luas_persegi(sisi):
    return sisi * sisi

def hitung_luas_persegi_panjang(panjang, lebar):
    return panjang * lebar

def hitung_luas_lingkaran(jari_jari):
    return 3.141592653589793 * jari_jari * jari_jari

def hitung_luas_segitiga(alas, tinggi):
    return 0.5 * alas * tinggi

def hitung_luas_jajar_genjang(alas, tinggi):
    return alas * tinggi

def hitung_luas_trapesium(sisi_a, sisi_b, tinggi):
    return 0.5 * (sisi_a + sisi_b) * tinggi

# Widget input untuk nama
input_nama = widgets.Text(
    value='',
    placeholder='Masukkan nama Anda',
    description='Nama:',
    disabled=False
)

btn_mulai = widgets.Button(description="Mulai")
output = widgets.Output()

def mulai_clicked(b):
    with output:
        clear_output()
        nama = input_nama.value.strip()
        if not nama:
            print("Mohon masukkan nama Anda terlebih dahulu.")
            return
        print(f"Halo, {nama}! Silakan pilih bangun datar untuk menghitung luasnya.")
        tampilkan_menu(nama)

def tampilkan_menu(nama):
    pilihan_bangun = widgets.Dropdown(
        options=[
            ('Persegi', 1),
            ('Persegi Panjang', 2),
            ('Lingkaran', 3),
            ('Segitiga', 4),
            ('Jajar Genjang', 5),
            ('Trapesium', 6),
            ('Selesai', 7)
        ],
        description='Bangun:',
        disabled=False,
    )
    btn_hitung = widgets.Button(description='Hitung Luas')
    result_out = widgets.Output()
    ukuran_widgets = []

    def update_ukuran_widgets(change):
        pilihan = change['new']
        # Hapus widget lama
        for w in ukuran_widgets:
            w.close()
        ukuran_widgets.clear()
        result_out.clear_output()

        if pilihan == 1:  # Persegi
            sisi = widgets.FloatText(description='Sisi:', value=0)
            ukuran_widgets.append(sisi)
            display(*ukuran_widgets)

        elif pilihan == 2:  # Persegi Panjang
            panjang = widgets.FloatText(description='Panjang:', value=0)
            lebar = widgets.FloatText(description='Lebar:', value=0)
            ukuran_widgets.extend([panjang, lebar])
            display(*ukuran_widgets)

        elif pilihan == 3:  # Lingkaran
            jari_jari = widgets.FloatText(description='Jari-jari:', value=0)
            ukuran_widgets.append(jari_jari)
            display(*ukuran_widgets)

        elif pilihan == 4:  # Segitiga
            alas = widgets.FloatText(description='Alas:', value=0)
            tinggi = widgets.FloatText(description='Tinggi:', value=0)
            ukuran_widgets.extend([alas, tinggi])
            display(*ukuran_widgets)

        elif pilihan == 5:  # Jajar Genjang
            alas = widgets.FloatText(description='Alas:', value=0)
            tinggi = widgets.FloatText(description='Tinggi:', value=0)
            ukuran_widgets.extend([alas, tinggi])
            display(*ukuran_widgets)

        elif pilihan == 6:  # Trapesium
            sisi_a = widgets.FloatText(description='Sisi a:', value=0)
            sisi_b = widgets.FloatText(description='Sisi b:', value=0)
            tinggi = widgets.FloatText(description='Tinggi:', value=0)
            ukuran_widgets.extend([sisi_a, sisi_b, tinggi])
            display(*ukuran_widgets)

        elif pilihan == 7:  # Selesai
            print(f"Terima kasih {nama}, telah menggunakan program ini.")
            btn_hitung.disabled = True
            pilihan_bangun.disabled = True
            for w in ukuran_widgets:
                w.close()
            ukuran_widgets.clear()

        # Display the button after updating the widgets
        display(btn_hitung)
        display(result_out)

    pilihan_bangun.observe(update_ukuran_widgets, names='value')

    def hitung_area(b):
        result_out.clear_output()
        pilihan = pilihan_bangun.value
        try:
            if pilihan == 1:  # Persegi
                sisi = ukuran_widgets[0].value
                if sisi <= 0:
                    raise ValueError("Sisi harus > 0")
                luas = hitung_luas_persegi(sisi)
                text = f'Luas persegi dengan sisi {sisi} adalah {luas:.2f}'
            elif pilihan == 2:  # Persegi Panjang
                panjang = ukuran_widgets[0].value
                lebar = ukuran_widgets[1].value
                if panjang <= 0 or lebar <= 0:
                    raise ValueError("Panjang dan lebar harus > 0")
                luas = hitung_luas_persegi_panjang(panjang, lebar)
                text = f'Luas persegi panjang {panjang} x {lebar} adalah {luas:.2f}'
            elif pilihan == 3:  # Lingkaran
                jari_jari = ukuran_widgets[0].value
                if jari_jari <= 0:
                    raise ValueError("Jari-jari harus > 0")
                luas = hitung_luas_lingkaran(jari_jari)
                text = f'Luas lingkaran dengan jari-jari {jari_jari} adalah {luas:.2f}'
            elif pilihan == 4:  # Segitiga
                alas = ukuran_widgets[0].value
                tinggi = ukuran_widgets[1].value
                if alas <= 0 or tinggi <= 0:
                    raise ValueError("Alas dan tinggi harus > 0")
                luas = hitung_luas_segitiga(alas, tinggi)
                text = f'Luas segitiga dengan alas {alas} dan tinggi {tinggi} adalah {luas:.2f}'
            elif pilihan == 5:  # Jajar Genjang
                alas = ukuran_widgets[0].value
                tinggi = ukuran_widgets[1].value
                if alas <= 0 or tinggi <= 0:
                    raise ValueError("Alas dan tinggi harus > 0")
                luas = hitung_luas_jajar_genjang(alas, tinggi)
                text = f'Luas jajar genjang dengan alas {alas} dan tinggi {tinggi} adalah {luas:.2f}'
            elif pilihan == 6:  # Trapesium
                sisi_a = ukuran_widgets[0].value
                sisi_b = ukuran_widgets[1].value
                tinggi = ukuran_widgets[2].value
                if sisi_a <= 0 or sisi_b <= 0 or tinggi <= 0:
                    raise ValueError("Sisi a, sisi b, dan tinggi harus > 0")
                luas = hitung_luas_trapesium(sisi_a, sisi_b, tinggi)
                text = f'Luas trapesium dengan sisi a {sisi_a}, sisi b {sisi_b} dan tinggi {tinggi} adalah {luas:.2f}'
            elif pilihan == 7:
                text = f"Terima kasih {nama}, sampai jumpa!"
                btn_hitung.disabled = True
                pilihan_bangun.disabled = True
                for w in ukuran_widgets:
                    w.close()
                ukuran_widgets.clear()
            else:
                text = "Pilihan tidak valid."
        except ValueError as e:
            text = f"Error: {str(e)}"
        with result_out:
            print(text)

    btn_hitung.on_click(hitung_area)

    # Initial display
    display(pilihan_bangun)
    update_ukuran_widgets({'new': pilihan_bangun.value})
    display(result_out)

btn_mulai.on_click(mulai_clicked)
display(input_nama, btn_mulai, output)